pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzerias.urls'))
]

pizzeria/pizzerias/urls.py
"""Defines URL patterns for pizzerias"""

from django.urls import path

from . import views

app_name='pizzerias'
urlpatterns=[
    #Home page
    path('',views.index, name='index'),
    # Page that shows all topics.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detail page for a single topic.
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria/pizzerias/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
        
    def __str__(self):
        return self.name
    
class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name_plural = 'toppings'
        
    def __str__(self):
        return self.name

pizzeria/pizzerias/views.py
from django.shortcuts import render

from .models import Pizza

# Create your views here.

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzerias/index.html')

def pizzas(request):
    """Show all Pizzas."""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzerias/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzerias/pizza.html', context)

pizzeria/pizzerias/templates/pizzerias/base.html
<h1>Welcome to my wonderful Pizzeria</h1>
<p> Please make your selection.. </p>
<p>
    <a href="{% url 'pizzerias:index' %}">Home |</a>
    <a href="{% url 'pizzerias:pizzas' %}">Pizza Selections</a>
</p>
{% block content %}{% endblock content%}

pizzeria/pizzerias/templates/pizzerias/index.html
{% extends "pizzerias/base.html" %}


{% block content %}

<p>Our pizzas are made with the finest ingredients</p>

{% endblock content %}

pizzeria/pizzerias/templates/pizzerias/pizza.html
{% extends 'pizzerias/base.html' %}

{% block content %}

<p>{{ pizza }} Pizza</p>

<p>Toppings:</p>
<ul>
{% for topping in toppings %}
    <li>
        <p>{{ topping.name|linebreaks }}</p>
    </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzeria/pizzerias/templates/pizzerias/pizzas.html
{% extends "pizzerias/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
        <li>
            <a href="{% url 'pizzerias:pizza' pizza.id %}">{{ pizza }}</a>
        </li>
    {% empty %}
        <li>No Pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}