bloggit/bloggit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('bloggits.urls')),
]

bloggit/bloggits/urls.py
"""Defines URL patterns for bloggits."""

from django.urls import path

from . import views

app_name = 'bloggits'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

bloggit/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

bloggit/bloggits/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."

bloggit/users/models.py
from django.db import models

# Create your models here.

bloggit/bloggits/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

bloggit/bloggits/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """The home page for Bloggit."""
    return render(request, 'bloggits/index.html')


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'bloggits/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'bloggits/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('bloggits:topics')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'bloggits/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect('bloggits:topic', topic_id=topic.id)
    
    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'bloggits/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('bloggits:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'bloggits/edit_entry.html', context)

bloggit/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('bloggits:index')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

bloggit/bloggits/templates/bloggits/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Bloggit</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
</head>
<body class="bg-light text-dark">

        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border-secondary">

            <a class="navbarbrand text-info" href="{% url 'bloggits:index' %}">
                Bloggit</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bloggits:topics' %}">
                            Subloggits</a></li>
                </ul>
                
                <ul class="navbar-nav m1-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>

        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content%}
            </div>

</body>
</html>

bloggit/bloggits/templates/bloggits/edit_entry.html
{% extends "bloggits/base.html" %}

{% block content %}

    <p><a class="text-info" href="{% url 'bloggits:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'bloggits:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info" name="submit">Save changes</button>
    </form>

{% endblock content %}

bloggit/bloggits/templates/bloggits/index.html
{% extends "bloggits/base.html" %}

{% block page_header %}
    <div class="jumbotron bg-dark">
        <h1 class="display-3 text-info">Welcome to Bloggit.</h1>

        <p class="lead text-light">The back page of the internet. Bloggit gives you the least of the 
            internet in one place. Get a rarely updating blog of useless information,
             just for you.</p>

        {% if user.is_authenticated %}

        {% else %}
            <a class="btn btn-lg btn-info" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>

         {% endif %}
        
    </div>

{% endblock page_header %}


{% block content %}

{% endblock content %}

bloggit/bloggits/templates/bloggits/new_entry.html
{% extends "bloggits/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new entry.</h2>
{% endblock page_header %}

{% block content %}

    <p><a href="{% url 'bloggits:topic' topic.id %}">{{ topic }}</a></p>

    <form action="{% url 'bloggits:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name='submit' class="btn btn-info">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

bloggit/bloggits/templates/bloggits/new_topic.html
{% extends "bloggits/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>New Topic</h3>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'bloggits:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-info">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

bloggit/bloggits/templates/bloggits/topic.html
{% extends 'bloggits/base.html' %}
{% load humanize %}

{% block page_header %}
    <h3>Welcome to {{ topic}} Subloggit</h3>
    <small>Posted by u/{{ topic.owner }}</small>
{% endblock page_header %}

{% block content %}

<p>
    <a class="text-info" href="{% url 'bloggits:new_entry' topic.id %}">Add new entry</a>
</p>

<ul>
{% for entry in entries %}
    <div class="card mb-3">
        <h5 class="card-header bg-dark text-info">
            u/{{ entry.owner }} <small>{{ entry.date_added|naturaltime }}</small>
            
        </h4>
        <div class="card-body">
        
        {{ entry.text|linebreaks }}
        
        </div>
        <div>
            {% if user == entry.owner %}
        <div class='p-2'>
        <p class="text-right">
        <small><a class="text-info" href="{% url 'bloggits:edit_entry' entry.id %}">Edit entry</a></small>
        </p>
    </div>
    {% else %}
    {% endif %}
        </div>
        
            
    </div>

    
    {% empty %}
        <p>There are no entries for this subloggit yet.</p>
    {% endfor %}
</ul>

{% endblock content %}

bloggit/bloggits/templates/bloggits/topics.html
{% extends "bloggits/base.html" %}

{% block page_header %}

    <h1>Subloggits</h1>
    <p><a class="text-info" href="{% url 'bloggits:new_topic' %}">Add a new subloggit</a></p>

{% endblock page_header %}


{% block content %}
<div>
<ul>
    {% for topic in topics %}
        <li><h3>
            <a class="text-info mb-4" href="{% url 'bloggits:topic' topic.id %}">{{ topic }}</a>
        </hs></li>
    {% empty %}
        <li><h3>No subloggits have been added yet.</h3></li>
    {% endfor %}
</ul>
</div>


{% endblock content %}